server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://aws.c0nbiodzldzr.ap-northeast-1.rds.amazonaws.com:3306/micro
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      dialect : org.hibernate.dialect.MySQL5InnoDBDialect
      